### ISSUE TITLE
Upgrade to 3.1.2 failure

### ISSUE THREAD

**Issue by fact0real** [iredmail/mlmmjadmin#18]
Hi all, 
When I upgrade the 3.0.6 to 3.1.2 I got this error message:

```
Traceback (most recent call last):
  File "tools/sync_profiles_to_db.py", line 251, in <module>
    qr = sync_owners(mail, owners)
  File "tools/sync_profiles_to_db.py", line 234, in sync_owners
    address_type="owner")
  File "tools/sync_profiles_to_db.py", line 182, in __sync_addresses
    where="address=$mail")
  File "/usr/local/lib/python3.5/dist-packages/web/db.py", line 1175, in delete
    self._db_execute(db_cursor, q)
  File "/usr/local/lib/python3.5/dist-packages/web/db.py", line 764, in _db_execute
    out = cur.execute(query, params)
psycopg2.ProgrammingError: relation "maillist_owners" does not exist
LINE 1: DELETE FROM maillist_owners WHERE address='*****@********'
```
How I can fix it?

**Comment by iredmail** [comment]
It requires SQL structure changes introduced in newer iRedMail release, please upgrade iRedMail by following our upgrade tutorials: https://docs.iredmail.org/iredmail.releases.html 

SQL column `mailbox.maillist_owners` was introduced in iRedMail-1.4.0:
https://docs.iredmail.org/upgrade.iredmail.1.3.2-1.4.0.html#add-new-sql-table-vmailmaillist_owners-and-drop-4-unused-columns

**Comment by fact0real** [comment]
I got new error too:
```
* Sync mailing list profiles to SQL/LDAP.
Traceback (most recent call last):
  File "tools/sync_profiles_to_db.py", line 251, in <module>
    qr = sync_owners(mail, owners)
  File "tools/sync_profiles_to_db.py", line 234, in sync_owners
    address_type="owner")
  File "tools/sync_profiles_to_db.py", line 182, in __sync_addresses
    where="address=$mail")
  File "/usr/local/lib/python3.5/dist-packages/web/db.py", line 1175, in delete
    self._db_execute(db_cursor, q)
  File "/usr/local/lib/python3.5/dist-packages/web/db.py", line 764, in _db_execute
    out = cur.execute(query, params)
psycopg2.ProgrammingError: permission denied for relation maillist_owners
```

**Comment by iredmail** [comment]
Permission issue. What's the owner of the newly created SQL table `maillist_owners`?

**Comment by fact0real** [comment]
I don't know, how I can check the owner of the mentioned SQL table?
