### ISSUE TITLE
module 'settings' has no attribute 'iredmail_sql_db_type'

### ISSUE THREAD

**Issue by VitaliySerov** [iredmail/mlmmjadmin#23]
Hi

on upgrading mlmmjadmin to v3.2.0 I got this error:
```
* Sync mailing list profiles to SQL/LDAP.
Traceback (most recent call last):
  File "tools/sync_profiles_to_db.py", line 61, in <module>
    from bk_iredmail_sql import SQLWrap
  File "/opt/mlmmjadmin-3.2.0/tools/../backends/bk_iredmail_sql.py", line 83, in <module>
    if settings.iredmail_sql_db_type == 'mysql':
AttributeError: module 'settings' has no attribute 'iredmail_sql_db_type'
* Upgrading completed.
```

Full log of upgrade:
<details>

```
# bash upgrade_mlmmjadmin.sh
* Detected Linux/BSD distribution: UBUNTU
Install package: python3 python3-pip python3-requests uwsgi-plugin-python3 python3-pymysql
* Found mlmmjadmin: /opt/mlmmjadmin, symbol link of /opt/mlmmjadmin-3.1.5
* Found old config file: /opt/mlmmjadmin/settings.py
* Copying new version to /opt/mlmmjadmin-3.2.0
* Copy /opt/mlmmjadmin/settings.py.
* Removing old symbol link /opt/mlmmjadmin
* Creating symbol link: /opt/mlmmjadmin-3.2.0 -> /opt/mlmmjadmin
* Copy systemd service file.
'/opt/mlmmjadmin/rc_scripts/systemd/debian.service' -> '/lib/systemd/system/mlmmjadmin.service'
Created symlink /etc/systemd/system/multi-user.target.wants/mlmmjadmin.service -> /lib/systemd/system/mlmmjadmin.service.
* mlmmjadmin has been successfully upgraded.
* Restarting service: mlmmjadmin.
* Sync mailing list profiles to SQL/LDAP.
Traceback (most recent call last):
  File "tools/sync_profiles_to_db.py", line 61, in <module>
    from bk_iredmail_sql import SQLWrap
  File "/opt/mlmmjadmin-3.2.0/tools/../backends/bk_iredmail_sql.py", line 83, in <module>
    if settings.iredmail_sql_db_type == 'mysql':
AttributeError: module 'settings' has no attribute 'iredmail_sql_db_type'
* Upgrading completed.
<<< NOTE >>> If mlmmjadmin doesn't work as expected, please post your issue in
<<< NOTE >>> our online support forum: http://www.iredmail.org/forum/
```
</details>

**Comment by iredmail** [comment]
- Do you have parameter `iredmail_sql_db_type` in file `/opt/mlmmjadmin-3.2.0/settings.py`?
- Are you running an old iRedMail release before iRedMail-0.9.8?

**Comment by VitaliySerov** [comment]
> Do you have parameter iredmail_sql_db_type in file /opt/mlmmjadmin-3.2.0/settings.py?

Nope

> Are you running an old iRedMail release before iRedMail-0.9.8?

Nope, upgrading from 1.5.2

**Comment by VitaliySerov** [comment]
Previous upgrades (to v1.5.2) was done by some other people, so I will not be surprised that someone missed some steps while upgrading some previous version of iRedMail (the server is quite old for sure and in some time in past I think iRedMail-0.9.8 was installed there)

But I see that upsteam file:
https://github.com/iredmail/mlmmjadmin/blob/master/libs/default_settings.py

Also missing this param?

**Comment by iredmail** [comment]
FYI https://docs.iredmail.org/integration.mlmmj.mysql.html

**Comment by VitaliySerov** [comment]
Thanks, probably this step was completly missed during the installation/upgrade
I think we can close that issue
